"""
URL routing for the api app.

All endpoints are prefixed with /api/ (set in fittrack/urls.py).
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

# ── Router auto-generates CRUD URLs for viewsets ─────────────────
router = DefaultRouter()
router.register(r"plans", views.TrainingPlanViewSet, basename="plan")
router.register(r"exercises", views.ExerciseViewSet, basename="exercise")
router.register(r"sessions", views.WorkoutSessionViewSet, basename="session")
router.register(r"logs", views.ExerciseLogViewSet, basename="log")

urlpatterns = [
    # Auth
    path("auth/register/", views.RegisterView.as_view(), name="register"),
    path("auth/login/", views.login_view, name="login"),
    path("auth/me/", views.me_view, name="me"),

    # CRUD (auto-generated by router)
    path("", include(router.urls)),

    # Progress / charts
    path(
        "progress/exercise/<int:exercise_id>/",
        views.exercise_progress,
        name="exercise-progress",
    ),
    path("progress/weekly/", views.weekly_volume, name="weekly-volume"),
    path("progress/dashboard/", views.dashboard, name="dashboard"),
]
